
py_binary(
    name = 'playpen',
    srcs = [
        'playpen.py'
    ],
    deps = [
        ':libs'
    ]
)

py_library(
    name = 'libs',
    srcs = [
        'cpp_template.py',
        'java_template.py',
        'python_template.py'
    ]
)
